version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.11.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t rocker/ropensci .

